### ISSUE TITLE
[BUG/Question] Pydantic validation error on email/acr

### ISSUE THREAD

**Issue by jorisstander** [Intility/fastapi-azure-auth#195] opened 2024-06-11 08:21 UTC
**Describe the bug**
I am having issues with the validation of my id token. The id token I receive from my B2C azure AD has 2 fields that fail in the validation:
1. Email - The email I receive is in a list of strings instead of a string. I contacted the 3rd party who are the owners of the B2C application and they say that this is the standard way of giving the email back. Example:
```
"email": [
    "example@exaple.com"
  ],
```
2. Acr - acr returns the protocol name instead of an optional literal. If im correct you can configure this in the application to `TFP`. [source](https://stackoverflow.com/questions/46688455/in-azure-ad-b2c-should-the-acr-or-tfp-claim-have-the-policy-name)

My questions are: 
Is returning an email in a list the standard way when it comes to a B2C id token? If not ill have to ask them to change this.
Will changing the setting from `acr` to `tfp` fix my issue with that validation?

In my code I am using `B2CMultiTenantAuthorizationCodeBearer` to verify this id token.
I wish I could provide more information about the configuration of azure ad set up but I do not have access to this.

**Stacktrace**
```
File "/usr/local/lib/python3.12/site-packages/fastapi_azure_auth/auth.py", line 212, in __call__
user: User = User(
             ^^^^^
File "/usr/local/lib/python3.12/site-packages/pydantic/main.py", line 176, in __init__
self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 2 validation errors for User
email
Input should be a valid string [type=string_type, input_value=['example@example.com'], input_type=list]
For further information visit https://errors.pydantic.dev/2.7/v/string_type
acr
Input should be '0' or '1' [type=literal_error, input_value='b2c_1a_displaycontrol_sendgrid_signin_hb', input_type=str]
For further information visit https://errors.pydantic.dev/2.7/v/literal_error
```

**Comment by JonasKs** [comment] 2024-06-11 16:39
Hi!

1. I've never seen `email` as a `list[str]`, can you please show a decoded token and give me an example on how to reproduce? 

2. `acr` is documented to only exist in v1 tokens, and to only have `0` and `1`. I were unable to find any Azure docs saying otherwise for B2C?  https://learn.microsoft.com/en-us/entra/identity-platform/access-token-claims-reference 


I wouldn't be surprised if Azure has changed these things though..  
Anyway, I'm happy to accept PRs for fixes - but I'd really prefer some official docs on intended behavior before we do so.

**Comment by JonasKs** [comment] 2024-06-23 11:16
Closing. Please reopen if this is still an issue, and provide the answers to the questions above.

**Closed by JonasKs** 2024-06-23 11:16 UTC
Labels: question
