### ISSUE TITLE
[Question] Following https://intility.github.io/fastapi-azure-auth/usage-and-faq/calling_your_apis_from_python/#single--and-multi-tenant but getting Invalid audience

### ISSUE THREAD

**Issue by elisabetao** [Intility/fastapi-azure-auth#198] opened 2024-07-02 22:18 UTC
**Describe the question**
I was able to setup the API interactive flow with PkceWithAuthorizationCodeGrant as listed here:https://intility.github.io/fastapi-azure-auth/single-tenant/fastapi_configuration/  for Single Tenant with SingleTenantAzureAuthorizationCodeBearer. However, when trying to use the code here https://intility.github.io/fastapi-azure-auth/usage-and-faq/calling_your_apis_from_python/#single--and-multi-tenant , while configuring another Azure Service Principal/App (similar to the OpenAPi one)  to connect to the backend API I get  : 
"INFO:fastapi_azure_auth:Token contains invalid claims. Invalid audience
2024-07-02T21:48:14.227784883Z INFO:     172.16.11.149:46006 - "GET /test HTTP/1.1" 401 Unauthorized"

In the Calling Your APIs from Python article, mentioned above,   it is mentioned that a new Azure application/Service principal identical or similar  to the OPENAPI one should work for the client_credentials flow, however checking the doc:https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth2-client-creds-grant-flow#application-permissions and https://thecibrax.com/oauth-client-credentials-in-azure-ad-explained-for-web-api-developers , my understanding is that  one needs to use application permissions and not delegated permissions when authenticating as an application:"When authenticating as an application (as opposed to with a user), you can't use delegated permissions because there is no user for your app to act on behalf of. You must use application permissions, also known as app roles, that are granted by an admin or by the API's owner."

I have created the app role and granted the app permissions to the new client/openapi application/service principal, however there's an error with teh audience I can't seem to be able to track as on my side the scope is set to the "api://BACKEND_APP_CLIENT_ID/.default", the same one that the other OPENAPI uses successfully for the Swagger.
Below is a sample of the token that encounters audience issues.

![image](https://github.com/Intility/fastapi-azure-auth/assets/24717881/2512b498-969e-4f51-8dc9-f068d30f5cb6)

I have already checked and reviewed a few times : https://github.com/Intility/fastapi-azure-auth/issues/156 and https://github.com/Intility/fastapi-azure-auth/issues/47 and these cases to do not appear to apply.

Would you have other suggestions to track this token audience issues?
Thanks a lot 

**To Reproduce**

**Stack trace**
"INFO:fastapi_azure_auth:Token contains invalid claims. Invalid audience
2024-07-02T21:48:14.227784883Z INFO:     172.16.11.149:46006 - "GET /test HTTP/1.1" 401 Unauthorized"

**Your configuration**

**Comment by JonasKs** [comment] 2024-07-03 08:09
I'm on vacation, so won't be able to reproduce for a while. 

Can you check that your `aud` matches the client ID of your backend (not swagger)? 

Your apps should indeed use the `api://<backend client ID>/.default`-scope, and receive a token with `aud` set to the `<backend client ID>`.

**Comment by elisabetao** [comment] 2024-07-03 12:19
Hi Jonas, 

Enjoy your vacations. Indeed aud /audience  matches the backed and client id.

Thanks

**Comment by JonasKs** [comment] 2024-07-03 15:37
Then I suspect your settings might be wrong in the backend app? 

Can you double check that the client ID in this section is your backend app(same as audience)?

```

azure_scheme = MultiTenantAzureAuthorizationCodeBearer(
    app_client_id=settings.APP_CLIENT_ID,  #<-------- this is the audience
    scopes={
        f'api://{settings.APP_CLIENT_ID}/user_impersonation': 'user_impersonation',
    },
    validate_iss=False
)
```

**Comment by elisabetao** [comment] 2024-07-03 17:46
Yes, the backend API APP client id matches the APP_CLIENT_ID , the api://<backend client ID>/.default and the audience  I set when trying to connect like so https://intility.github.io/fastapi-azure-auth/usage-and-faq/calling_your_apis_from_python/#single--and-multi-tenant with this code

**Comment by JonasKs** [comment] 2024-07-03 19:00
Not sure to be honest. I'd start over with a mini project and make sure the tutorial is followed to the exact point, no alterations.

**Comment by JonasKs** [comment] 2024-07-12 13:56
I just tested this out with a Single Tenant appreg, created a ClientSecret in my OpenAPI appreg, and copy/pasted the code. It worked.

I hope you figure it out, but I can't reproduce. Feel free to comment(I'll still get notifications), but I'll close the issue.

**Closed by JonasKs** 2024-07-12 13:56 UTC
Labels: question

**Comment by elisabetao** [comment] 2024-07-12 20:09
Hi Jonas, Thanks for the help.  I have managed to solve by following partly your doc: https://intility.github.io/fastapi-azure-auth/usage-and-faq/calling_your_apis_from_python/#single--and-multi-tenant ,partly :https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth2-client-creds-grant-flow#application-permissions  and partly enabling more debugging on jwt audience . The issue in my case was that the application permissions had to be set on the OpenAPI Azure app and not the Backend app as it was my audience.

Thanks once again for your time, feedback and support

**Comment by JonasKs** [comment] 2024-07-13 06:33
Glad you solved it 😊 have a nice weekend!

**Comment by simon-jones-nyc** [comment] 2024-09-18 21:04
For anyone struggling with a similar issue with Azure B2C configuration, ensure you use the App Registration Client ID for your backend API in the scope, like this:

https://${settings.TENANT_NAME}.onmicrosoft.com/${settings.API_ID}/user_impersonation

**Comment by itisguptak** [comment] 2024-09-23 14:31
Well, I saw this post which says that version should be changed to v2.0 in manifest file. I need to check that. May be I didn't follow the Azure config word by word :) because I do not have permissions to do it myself. 

https://stackoverflow.com/questions/59790209/access-token-issuer-from-azure-ad-is-sts-windows-net-instead-of-login-microsofto
